"""
GS bull/bear throttle on top of the Investment Clock.

The clock (growth × inflation → goldilocks / reflation / stagflation /
deflation) remains the only position engine. This module does not build a
second weight table and does not average two regime engines.

GSBLBR, as generated by ``scripts/generate_gsblbr.py``, is a public proxy for
the Goldman Sachs Bull/Bear *risk* indicator — not a feed from a GS terminal.
It is the equal-weight average of five causal expanding-window percentiles
(min 60 months), each dated at observation month-end:

  1. Shiller valuation proxy — S&P 500 / trailing 10-year average price
  2. Yield-curve inversion — −1 × (10Y − 2Y), FRED T10Y2Y
  3. Core CPI year-over-year, FRED CPILFESL
  4. Labor tightness — −1 × unemployment rate, FRED UNRATE
  5. Economic activity — industrial production year-over-year, FRED INDPRO

A high composite means late-cycle stress (stretched valuation, inversion,
hot inflation, tight labor, strong activity). A low composite means a
washout / trough, not "the market is currently falling". 2008–09 prints are
very low; 2022 prints are very high. That is the intended economic meaning
of the bands below.

The backtest applies ``release_lag_months`` (default 1) before the score may
be used, because CPI, unemployment, and industrial production are not known
on the observation month-end.
"""

from __future__ import annotations

from typing import Optional

import numpy as np
import pandas as pd

from config.regime_rules import (
    GS_THROTTLE_EQUITY_TICKERS,
    GS_THROTTLE_PARAMS,
    REGIME_WEIGHTS,
)


def release_gs_score(score: pd.Series, lag_months: int = 1) -> pd.Series:
    """Shift a month-end GSBLBR composite to its usable release date.

    The returned index is the first date the print may be read. Callers
    must ``asof`` this series; they must not shift it a second time.
    """
    s = pd.to_numeric(score, errors="coerce").dropna().sort_index()
    if s.empty:
        return s
    s = s.copy()
    s.index = pd.to_datetime(s.index)
    if getattr(s.index, "tz", None) is not None:
        s.index = s.index.tz_localize(None)
    if lag_months:
        s.index = s.index + pd.DateOffset(months=int(lag_months))
    # A lagged month-end can collide with the next observation; keep the
    # later print so the series stays strictly as-of safe.
    s = s[~s.index.duplicated(keep="last")].sort_index()
    s.name = "GSBLBR"
    return s


def classify_gs_band(score, bull_max: float, bear_min: float) -> str:
    """Map a bear-risk percentile to bull / mid / bear.

    ``unknown`` (missing or non-finite) is a pass-through: the clock is
    left unchanged rather than inventing a derisk.
    """
    try:
        x = float(score)
    except (TypeError, ValueError):
        return "unknown"
    if not np.isfinite(x):
        return "unknown"
    if bull_max >= bear_min:
        raise ValueError(f"bull_max ({bull_max}) must be < bear_min ({bear_min})")
    if x >= bear_min:
        return "bear"
    if x < bull_max:
        return "bull"
    return "mid"


def _defense_park(deflation_weights: dict, equity: set[str]) -> dict[str, float]:
    """Non-equity slice of the Deflation book, renormalised to 1.

    Freed equity weight from a mid-band scale-down is parked here so the
    clock's equity *direction* shrinks without averaging in a second engine.
    """
    park = {k: float(v) for k, v in deflation_weights.items() if k not in equity and float(v) > 0}
    total = sum(park.values())
    if total <= 0:
        return {"IEF": 0.5, "GLD": 0.5}
    return {k: v / total for k, v in park.items()}


def _drop_tiny(weights: dict[str, float]) -> dict[str, float]:
    return {k: float(v) for k, v in weights.items() if float(v) > 1e-12}


def scale_equity_sleeve(
    weights: dict[str, float],
    scale: float,
    deflation_weights: dict[str, float],
    equity_tickers,
) -> dict[str, float]:
    """Scale the equity sleeve and keep gross exposure at 1.

    scale < 1: shrink equity, park the freed weight in the Deflation
    non-equity sleeve (IEF / GLD / DBMF).
    scale > 1: tilt toward equity by reducing non-equity pro-rata.
    Equity is capped at 98% so a ballast line remains.
    """
    equity = set(equity_tickers)
    w = {k: float(v) for k, v in weights.items()}
    eq_keys = [k for k in w if k in equity]
    eq_sum = sum(w[k] for k in eq_keys)
    if eq_sum <= 1e-12 or abs(scale - 1.0) < 1e-12:
        return w
    if scale < 1.0:
        for k in eq_keys:
            w[k] *= scale
        freed = eq_sum * (1.0 - scale)
        for k, share in _defense_park(deflation_weights, equity).items():
            w[k] = w.get(k, 0.0) + freed * share
        return _drop_tiny(w)

    target_eq = min(eq_sum * scale, 0.98)
    for k in eq_keys:
        w[k] *= target_eq / eq_sum
    non_keys = [k for k in w if k not in equity]
    non_sum = sum(w[k] for k in non_keys)
    remain = 1.0 - sum(w[k] for k in eq_keys)
    if non_sum > 1e-12 and remain >= 0:
        for k in non_keys:
            w[k] = w[k] / non_sum * remain
    else:
        gross = sum(w[k] for k in eq_keys) or 1.0
        for k in eq_keys:
            w[k] /= gross
        for k in non_keys:
            w[k] = 0.0
    return _drop_tiny(w)


def blend_toward_deflation(
    clock_weights: dict[str, float],
    deflation_weights: dict[str, float],
    alpha: float,
) -> dict[str, float]:
    """Override the clock toward its own Deflation table.

    alpha = 0 leaves the clock unchanged. alpha = 1 replaces it with the
    Deflation book. This is a defensive override, not a blend of two
    independent regime models.
    """
    alpha = float(np.clip(alpha, 0.0, 1.0))
    keys = set(clock_weights) | set(deflation_weights)
    out = {
        k: (1.0 - alpha) * float(clock_weights.get(k, 0.0))
        + alpha * float(deflation_weights.get(k, 0.0))
        for k in keys
    }
    total = sum(out.values())
    if total <= 0:
        return {}
    return {k: v / total for k, v in out.items() if v > 1e-12}


def apply_gs_throttle(
    clock_weights: dict[str, float],
    regime: str,
    score,
    params: dict,
) -> tuple[dict[str, float], float, Optional[float]]:
    """Return ``(weights, vol_mult, vol_hi)``.

    ``vol_hi is None`` means "use the strategy vol cap unchanged".
    When the band is unknown, or the bull band is an identity scale, the
    clock dict is returned as-is (not rebuilt) so a no-op month matches
    the unthrottled book.
    """
    band = classify_gs_band(score, params["bull_max"], params["bear_min"])
    if band == "unknown":
        return clock_weights, 1.0, None

    if band == "bull":
        risk_on = regime in params.get("risk_on_regimes", ("goldilocks", "reflation"))
        scale = float(params["bull_equity_scale"]) if risk_on else 1.0
        vol_mult = float(params["bull_vol_mult"]) if risk_on else 1.0
        vol_hi = params["bull_vol_hi"] if risk_on else None
        if abs(scale - 1.0) < 1e-12:
            return clock_weights, vol_mult, vol_hi
        tilted = scale_equity_sleeve(
            clock_weights, scale, params["deflation_weights"], params["equity_tickers"],
        )
        return tilted, vol_mult, vol_hi

    if band == "mid":
        scaled = scale_equity_sleeve(
            clock_weights,
            float(params["mid_equity_scale"]),
            params["deflation_weights"],
            params["equity_tickers"],
        )
        return scaled, float(params["mid_vol_mult"]), params["mid_vol_hi"]

    overridden = blend_toward_deflation(
        clock_weights, params["deflation_weights"], float(params["bear_blend"]),
    )
    return overridden, float(params["bear_vol_mult"]), params["bear_vol_hi"]


def build_engine_throttle(score: pd.Series, mode: str = "derisk", **overrides) -> dict:
    """Flat parameter dict accepted by ``run_optimized_regime_backtest(gs_throttle=...)``.

    ``mode`` is ``derisk`` (bull band = full clock) or ``boost`` (bull band
    scales equity and the vol target up when the clock is also risk-on).
    Keyword overrides replace a single flat key (band thresholds, scales).
    The embedded ``score`` series is already release-lagged.
    """
    if mode not in GS_THROTTLE_PARAMS["modes"]:
        raise KeyError(f"unknown GS throttle mode {mode!r}")
    flat_keys = (
        "bull_max", "bear_min", "release_lag_months", "mid_equity_scale",
        "mid_vol_mult", "mid_vol_hi", "bear_blend", "bear_vol_mult", "bear_vol_hi",
    )
    cfg = {k: GS_THROTTLE_PARAMS[k] for k in flat_keys}
    cfg.update(GS_THROTTLE_PARAMS["modes"][mode])
    cfg["risk_on_regimes"] = tuple(GS_THROTTLE_PARAMS["risk_on_regimes"])
    unknown = [k for k in overrides if k not in cfg]
    if unknown:
        raise KeyError(f"unknown GS throttle override(s): {unknown}")
    cfg.update(overrides)
    if float(cfg["bull_max"]) >= float(cfg["bear_min"]):
        raise ValueError("bull_max must be < bear_min")
    return {
        "score": release_gs_score(score, int(cfg["release_lag_months"])),
        "deflation_weights": dict(REGIME_WEIGHTS["deflation"]),
        "equity_tickers": tuple(GS_THROTTLE_EQUITY_TICKERS),
        "mode": mode,
        **cfg,
    }


def assert_throttle_identities() -> None:
    """Fast invariants used by the contrast script before any backtest."""
    clock = dict(REGIME_WEIGHTS["goldilocks"])
    defl = dict(REGIME_WEIGHTS["deflation"])
    params = build_engine_throttle(pd.Series([10.0], index=pd.to_datetime(["2020-01-31"])), mode="derisk")
    # Drop the series; apply_gs_throttle only needs the scalars.
    w, vm, vh = apply_gs_throttle(clock, "goldilocks", 10.0, params)
    assert w is clock and vm == 1.0 and vh is None, "derisk bull band must be a no-op"

    w, vm, vh = apply_gs_throttle(clock, "goldilocks", 55.0, params)
    assert abs(sum(w.values()) - 1.0) < 1e-8
    eq = sum(w[t] for t in w if t in GS_THROTTLE_EQUITY_TICKERS)
    base_eq = sum(clock[t] for t in clock if t in GS_THROTTLE_EQUITY_TICKERS)
    assert eq < base_eq - 0.05, "mid band must shrink the equity sleeve"
    assert vm == params["mid_vol_mult"] and vh == 1.0

    w, vm, vh = apply_gs_throttle(clock, "goldilocks", 80.0, params)
    assert abs(sum(w.values()) - 1.0) < 1e-8
    for t, weight in defl.items():
        assert abs(w.get(t, 0.0) - weight) < 1e-8, f"bear override mismatch on {t}"

    boost = build_engine_throttle(
        pd.Series([10.0], index=pd.to_datetime(["2020-01-31"])), mode="boost",
    )
    w, vm, vh = apply_gs_throttle(clock, "goldilocks", 10.0, boost)
    assert abs(sum(w.values()) - 1.0) < 1e-8
    eq = sum(w[t] for t in w if t in GS_THROTTLE_EQUITY_TICKERS)
    assert eq > base_eq + 0.05, "boost must raise equity when both are risk-on"
    assert vm == boost["bull_vol_mult"]
    # Defensive clock + bullish GS: do not boost. Clock stays primary.
    w, vm, vh = apply_gs_throttle(defl, "deflation", 10.0, boost)
    assert w is defl and vm == 1.0 and vh is None

    released = release_gs_score(pd.Series([80.0], index=pd.to_datetime(["2020-01-31"])), 1)
    # Observation month-end + 1 month. 2020 is a leap year, so Jan 31 → Feb 29.
    assert released.index[0] == pd.Timestamp("2020-02-29")
